[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.40.28",
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "python-multipart>=0.0.20",
]
